from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date

class CustomUser(AbstractUser):
    #EMP_ID, E_NAME, doj autogenerated by AbstractUser Class 
    username = None
    email = models.EmailField(unique=True)
    status = models.CharField(max_length=15)
    salary = models.DecimalField(max_digits=15, decimal_places=2)
    role = models.CharField(max_length=20, choices=[
        ('employer', 'Employer'),
        ('employee', 'Employee'),
    ])
    company = models.ForeignKey('Company', on_delete=models.SET_NULL, null=True, blank=True, related_name='users')
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    def __str__(self):
        return self.username 
    
class Company(models.Model):
    c_name = models.CharField(max_length=50)
    ceo_name = models.CharField(max_length=50)
    location = models.CharField(max_length=100)
    ticker = models.CharField(max_length=30)
    email = models.EmailField(max_length=30)
    social_mdata = models.CharField(max_length=100)
    
    def __str__(self):
        return self.email
        
class Listings(models.Model):
    l_role = models.CharField(max_length=50)
    l_name = models.CharField(max_length=50)
    est_salary = models.DecimalField(max_digits=15, decimal_places=2)
    apply_deadline = models.DateField(default=date.today)  
    
    company = models.ForeignKey('Company', on_delete=models.CASCADE, related_name = 'listings')
    skills = models.ManyToManyField('Skills', related_name='listings')

class Skills(models.Model):
    s_name = models.CharField(max_length=20)
    s_type = models.CharField(max_length=20)
    
class Work_Exp(models.Model):
    resume = models.ForeignKey('Resume', on_delete=models.CASCADE, related_name='work_exp')
    time_period = models.TimeField()
    position = models.CharField(max_length=30)
    workplace = models.CharField(max_length=30)
    

class Projects(models.Model):
    resume = models.ForeignKey('Resume', on_delete=models.CASCADE, related_name='projects')
    p_name = models.CharField(max_length=40)
    p_link = models.CharField(max_length=120)
    p_desc = models.CharField(max_length=500)
    

class Certifications(models.Model):
    resume = models.ForeignKey('Resume', on_delete=models.CASCADE, related_name='certifications')
    cer_name = models.CharField(max_length=50)
    credential = models.CharField(max_length=100)
    cer_desc = models.CharField(max_length=500)
    

class Education(models.Model):
    resume = models.ForeignKey('Resume', on_delete=models.CASCADE, related_name='education')
    e_type = models.CharField(max_length=20)
    year = models.DateField()
    grade = models.CharField(max_length=10)
    location = models.CharField(max_length=100)
    
class Resume(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='resume')
    biodata = models.CharField(max_length=400)
    github = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    phone = models.IntegerField()
    mail = models.EmailField(unique=True)
    
    #FOREIGN KEY MAPPING FOR RESUME ENTITY OFFSHOOTS
    skills = models.ManyToManyField('Skills', blank=True, related_name='resume')
