from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date
# Create your models here.
class CustomUser(AbstractUser):
    #EMP_ID, E_NAME, doj autogenerated by AbstractUser Class 
    username = None
    email = models.EmailField(unique=True)
    status = models.CharField(max_length=15)
    salary = models.DecimalField(max_digits=15, decimal_places=2)
    role = models.CharField(max_length=20, choices=[
        ('employer', 'Employer'),
        ('employee', 'Employee'),
    ])
    company = models.ForeignKey('Company', on_delete=models.SET_NULL, null=True, blank=True, related_name='users')
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    def __str__(self):
        return self.username 
class Company(models.Model):
    c_name = models.CharField(max_length=50)
    ceo_name = models.CharField(max_length=50)
    location = models.CharField(max_length=100)
    ticker = models.CharField(max_length=30)
    email = models.EmailField(max_length=30)
    social_mdata = models.CharField(max_length=100)
    
    def __str__(self):
        return self.c_name
        
class Listings(models.Model):
    l_role = models.CharField(max_length=50)
    l_name = models.CharField(max_length=50)
    est_salary = models.DecimalField(max_digits=15, decimal_places=2)
    apply_deadline = models.DateField(default=date.today)  
    company = models.ForeignKey('Company', on_delete=models.CASCADE, related_name = 'listings')
